app:
  jolt:
    trainingDetailsRequestJoltSpec: /TrainingDetailsRequestJoltSpec.json
    trainingDetailsGetResponseJoltSpec: /TrainingDetailsGetResponseJoltSpec.json
    trainingDetailsPostResponseJoltSpec: /TrainingDetailsPostResponseJoltSpec.json
